In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import confusion_matrix
from sklearn.metrics import precision_recall_fscore_support
from sklearn.metrics import accuracy_score

In [2]:
df=pd.read_csv('diabetes.csv')


In [3]:
df2=df.drop(['Pregnancies','Outcome'],axis=1)


In [5]:
df

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0              6      148             72             35        0  33.6   
1              1       85             66             29        0  26.6   
2              8      183             64              0        0  23.3   
3              1       89             66             23       94  28.1   
4              0      137             40             35      168  43.1   
..           ...      ...            ...            ...      ...   ...   
763           10      101             76             48      180  32.9   
764            2      122             70             27        0  36.8   
765            5      121             72             23      112  26.2   
766            1      126             60              0        0  30.1   
767            1       93             70             31        0  30.4   

     DiabetesPedigreeFunction  Age  Outcome  
0                       0.627   50        1  
1                       0.351   31        0  
2                       0.672   32        1  
3                       0.167   21        0  
4                       2.288   33        1  
..                        ...  ...      ...  
763                     0.171   63        0  
764                     0.340   27        0  
765                     0.245   30        0  
766                     0.349   47        1  
767                     0.315   23        0  

[768 rows x 9 columns]

In [6]:
#find a mean to replace missing values by mean (astype is use to change column type)
avg_insulin=df['Insulin'].astype("float").mean(axis=0)
avg_glucose=df['Glucose'].astype("float").mean(axis=0)
avg_bp=df['BloodPressure'].astype("float").mean(axis=0)
avg_skinthickness=df['SkinThickness'].astype("float").mean(axis=0)
avg_BMI=df['BMI'].astype("float").mean(axis=0)
avg_DPF=df['DiabetesPedigreeFunction'].astype("float").mean(axis=0)
avg_age=df['Age'].astype("float").mean(axis=0)

In [7]:
#replace zero insulin with mean
#print(avg_2)
df['Insulin'].replace(0,avg_insulin,inplace=True) #make it work to replace zero
df['Glucose'].replace(0,avg_glucose,inplace=True)
df['BloodPressure'].replace(0,avg_bp,inplace=True)
df['SkinThickness'].replace(0,avg_skinthickness,inplace=True)
df['BMI'].replace(0,avg_BMI,inplace=True)
df['DiabetesPedigreeFunction'].replace(0,avg_DPF,inplace=True)
df['Age'].replace(0,avg_age,inplace=True)

In [8]:
df

Pregnancies  Glucose  BloodPressure  SkinThickness     Insulin   BMI  \
0              6    148.0           72.0      35.000000   79.799479  33.6   
1              1     85.0           66.0      29.000000   79.799479  26.6   
2              8    183.0           64.0      20.536458   79.799479  23.3   
3              1     89.0           66.0      23.000000   94.000000  28.1   
4              0    137.0           40.0      35.000000  168.000000  43.1   
..           ...      ...            ...            ...         ...   ...   
763           10    101.0           76.0      48.000000  180.000000  32.9   
764            2    122.0           70.0      27.000000   79.799479  36.8   
765            5    121.0           72.0      23.000000  112.000000  26.2   
766            1    126.0           60.0      20.536458   79.799479  30.1   
767            1     93.0           70.0      31.000000   79.799479  30.4   

     DiabetesPedigreeFunction  Age  Outcome  
0                       0.627   50        1  
1                       0.351   31        0  
2                       0.672   32        1  
3                       0.167   21        0  
4                       2.288   33        1  
..                        ...  ...      ...  
763                     0.171   63        0  
764                     0.340   27        0  
765                     0.245   30        0  
766                     0.349   47        1  
767                     0.315   23        0  

[768 rows x 9 columns]

In [9]:
x=np.array(df.drop(['Outcome'],axis=1))#axis=1 means its a column
y=np.array(df['Outcome'])

In [10]:
#scaling
scaler = MinMaxScaler()
x_scaler=scaler.fit_transform(x)

In [11]:
print(x_scaler)

[[0.35294118 0.67096774 0.48979592 ... 0.31492843 0.23441503 0.48333333]
 [0.05882353 0.26451613 0.42857143 ... 0.17177914 0.11656704 0.16666667]
 [0.47058824 0.89677419 0.40816327 ... 0.10429448 0.25362938 0.18333333]
 ...
 [0.29411765 0.49677419 0.48979592 ... 0.16359918 0.07130658 0.15      ]
 [0.05882353 0.52903226 0.36734694 ... 0.24335378 0.11571307 0.43333333]
 [0.05882353 0.31612903 0.46938776 ... 0.24948875 0.10119556 0.03333333]]


In [12]:
x_train,x_test,y_train,y_test=train_test_split(x_scaler,y,test_size=0.2,random_state=0) #0.2 means test=20% train=80% selecting #start from 0 th record 


In [13]:
print(x_train)

[[0.41176471 0.68387097 0.55102041 ... 0.34764826 0.26216909 0.55      ]
 [0.23529412 0.34193548 0.36734694 ... 0.20449898 0.1558497  0.01666667]
 [0.         0.78064516 0.67346939 ... 0.69734151 0.14901793 0.03333333]
 ...
 [0.23529412 0.32258065 0.41836735 ... 0.13292434 0.02988898 0.        ]
 [0.64705882 0.26451613 0.51020408 ... 0.24335378 0.09479078 0.23333333]
 [0.29411765 0.59354839 0.59183673 ... 0.28205681 0.23996584 0.8       ]]


In [14]:
print(x_test)

[[0.05882353 1.         0.53061224 ... 0.50511247 0.56191289 0.01666667]
 [0.11764706 0.40645161 0.51020408 ... 0.31492843 0.13919727 0.03333333]
 [0.23529412 0.20645161 0.3877551  ... 0.32310838 0.13364646 0.06666667]
 ...
 [0.23529412 0.63225806 0.63265306 ... 0.52760736 0.24210077 0.01666667]
 [0.17647059 0.46451613 0.51020408 ... 0.16564417 0.01238258 0.05      ]
 [0.05882353 0.40645161 0.48979592 ... 0.25766871 0.31725021 0.05      ]]


In [15]:
classifier=GaussianNB()
classifier.fit(x_train,y_train)
y_predict=classifier.predict(x_test)

In [19]:
c=confusion_matrix(y_test,y_predict)
cf_df= pd.DataFrame(c,columns=['Predicted No','Predicted Yes'], index=['Actual No', 'Actual yes'])


In [20]:
print(cf_df)


            Predicted No  Predicted Yes
Actual No             92             15
Actual yes            19             28


In [22]:
prfs=precision_recall_fscore_support(y_test,y_predict)
acc=accuracy_score(y_test, y_predict)
print(acc)
print(prfs)

0.7792207792207793
(array([0.82882883, 0.65116279]), array([0.85981308, 0.59574468]), array([0.8440367 , 0.62222222]), array([107,  47], dtype=int64))
